#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错 
spring: 
  profiles: 
    active: dev # 激活开发环境配置 
#--- 
server: 
  port: 8001 #端口号 
mybatis: 
  #config-location: classpath:mybatis/mybatis.cfg.xml 
  #type-aliases-package: com.mengxuegu.springcloud.entities 
  mapper-locations: classpath:/mapper/*.xml
spring:
  profiles: dev # 开发环境	
  application:
    name: fffapi8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.3.12.6:3306/java0902?serverTimezone=GMT%2B8
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: true #服务注册，false表示不将自已注册到Eureka服务中
    fetch-registry: true #服务发现，false表示自己不从Eureka服务中获取注册信息
    service-url:
      defaultZone: http://eurekaser6001.com:6001/eureka/,http://eurekaser6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}-hystrix8071 #指定实例ID,就不会显示主
    prefer-ip-address: true #访问路径可以显示IP地址
#-----------------
server: 
  port: 8001 #端口号 
mybatis: 
  #config-location: classpath:mybatis/mybatis.cfg.xml 
  #type-aliases-package: com.mengxuegu.springcloud.entities 
  mapper-locations: classpath:/mapper/*.xml
spring:
  profiles: prod # 开发环境	
  application:
    name: fffapi8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.3.12.6:3306/java0902?serverTimezone=GMT%2B8
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: true #服务注册，false表示不将自已注册到Eureka服务中
    fetch-registry: true #服务发现，false表示自己不从Eureka服务中获取注册信息
    service-url:
      defaultZone: http://eurekaser6001.com:6001/eureka/,http://eurekaser6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}-hystrix8071 #指定实例ID,就不会显示主
    prefer-ip-address: true #访问路径可以显示IP地址
