spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservice-config-dev
---
server:
  port: 8002
spring:
  profiles: prod
  application:
    name: microservice-config-prod